ig.countryNames =
  "Afghanistan"                              : "Afghánistán"
  "other"                                    : "ostatní"
  "Australia"                                : "Austrálie"
  "Austria"                                  : "Rakousko"
  "Canada"                                   : "Kanada"
  "Switzerland"                              : "Švýcarsko"
  "China"                                    : "Čína"
  "Lao People's Dem. Rep."                   : "Laos"
  "Viet Nam"                                 : "Vietnam"
  "Dem. Rep. of the Congo"                   : "Dem. Rep. Kongo"
  "Angola"                                   : "Angola"
  "Burundi"                                  : "Burundi"
  "Rwanda"                                   : "Rwanda"
  "Sudan"                                    : "Súdán"
  "Uganda"                                   : "Uganda"
  "Germany"                                  : "Německo"
  "Algeria"                                  : "Alžírsko"
  "Western Sahara"                           : "Západní Sahara"
  "Palestinian"                              : "Palestina"
  "Spain"                                    : "Španělsko"
  "Ethiopia"                                 : "Etiopie"
  "Somalia"                                  : "Somálsko"
  "Finland"                                  : "Finsko"
  "France"                                   : "Francie"
  "United Kingdom"                           : "Anglie"
  "Colombia"                                 : "Kolumbie"
  "Czech Rep."                               : "Česko"
  "Ghana"                                    : "Ghana"
  "India"                                    : "Indie"
  "Iran (Islamic Rep. of)"                   : "Írán"
  "Iraq"                                     : "Irák"
  "Lebanon"                                  : "Libanon"
  "Libya"                                    : "Libye"
  "Sri Lanka"                                : "Sri Lanka"
  "Pakistan"                                 : "Pákistán"
  "Poland"                                   : "Polsko"
  "Romania"                                  : "Rumunsko"
  "El Salvador"                              : "El Salvador"
  "Seychelles"                               : "Seychely"
  "Turkey"                                   : "Krocan"
  "South Africa"                             : "Jižní Afrika"
  "Guinea"                                   : "Guinea"
  "Liberia"                                  : "Libérie"
  "Greece"                                   : "Řecko"
  "Jordan"                                   : "Jordán"
  "Kenya"                                    : "Keňa"
  "Mozambique"                               : "Mosambik"
  "Namibia"                                  : "Namibie"
  "Luxembourg"                               : "Lucembursko"
  "Malawi"                                   : "Malawi"
  "Netherlands"                              : "Nizozemsko"
  "Norway"                                   : "Norsko"
  "Portugal"                                 : "Portugalsko"
  "Chad"                                     : "Chad"
  "Serbia and Kosovo (S/RES/1244 (1999))"    : "Srbsko a Kosovo"
  "Albania"                                  : "Albánie"
  "Sweden"                                   : "Švédsko"
  "Argentina"                                : "Argentina"
  "Bangladesh"                               : "Bangladéš"
  "Bulgaria"                                 : "Bulharsko"
  "Bolivia (Plurinational State of)"         : "Bolívie"
  "Chile"                                    : "Chile"
  "Guatemala"                                : "Guatemala"
  "Hungary"                                  : "Maďarsko"
  "Cambodia"                                 : "Kambodža"
  "Kuwait"                                   : "Kuvajt"
  "Peru"                                     : "Peru"
  "Russian Federation"                       : "Rusko"
  "Syrian Arab Rep."                         : "Sýrie"
  "Uruguay"                                  : "Uruguay"
  "United Rep. of Tanzania"                  : "Tanzanie"
  "United States of America"                 : "Spojené státy americké"
  "Cuba"                                     : "Kuba"
  "Nicaragua"                                : "Nikaragua"
  "Panama"                                   : "Panama"
  "Equatorial Guinea"                        : "Rovníková Guinea"
  "Sierra Leone"                             : "Sierra Leone"
  "Saudi Arabia"                             : "Saudská Arábie"
  "Eritrea"                                  : "Eritrea"
  "Egypt"                                    : "Egypt"
  "Tunisia"                                  : "Tunisko"
  "Tajikistan"                               : "Tádžikistán"
  "Armenia"                                  : "Arménie"
  "Azerbaijan"                               : "Ázerbajdžán"
  "Zambia"                                   : "Zambie"
  "Mali"                                     : "Mali"
  "Niger"                                    : "Niger"
  "Croatia"                                  : "Chorvatsko"
  "Bosnia and Herzegovina"                   : "Bosna a Hercegovina"
  "The former Yugoslav Republic of Macedonia": "Makedonie"
  "Indonesia"                                : "Indonésie"
  "Suriname"                                 : "Surinam"
  "Slovenia"                                 : "Slovinsko"
  "Estonia"                                  : "Estonsko"
  "Haiti"                                    : "Haiti"
  "Myanmar"                                  : "Myanmar"
  "Georgia"                                  : "Gruzie"
  "Tibetan"                                  : "Tibet"
  "Slovakia"                                 : "Slovensko"
  "Morocco"                                  : "Maroko"
  "Ukraine"                                  : "Ukrajina"
  "Cameroon"                                 : "Kamerun"
  "Fiji"                                     : "Fidži"
  "Honduras"                                 : "Honduras"
  "Philippines"                              : "Filipíny"
  "Costa Rica"                               : "Kostarika"
  "Djibouti"                                 : "Džibutsko"
  "Ecuador"                                  : "Ekvádor"
  "Guyana"                                   : "Guyana"
  "China, Hong Kong SAR"                     : "Hong Kong"
  "Israel"                                   : "Izrael"
  "Italy"                                    : "Itálie"
  "Latvia"                                   : "Lotyšsko"
  "Rep. of Moldova"                          : "Moldavsko"
  "Mexico"                                   : "Mexiko"
  "Malaysia"                                 : "Malajsie"
  "Nigeria"                                  : "Nigérie"
  "Qatar"                                    : "Katar"
  "Togo"                                     : "Togo"
  "Thailand"                                 : "Thajsko"
  "Venezuela (Bolivarian Republic of)"       : "Venezuela"
  "Yemen"                                    : "Jemen"
  "C�te d'Ivoire"                            : "Pobřeží slonoviny"
  "Kazakhstan"                               : "Kazachstán"
  "Lithuania"                                : "Litva"
  "Uzbekistan"                               : "Uzbekistán"
  "Central African Rep."                     : "Středoafrická republika"
  "Congo"                                    : "Kongo"
  "Gambia"                                   : "Gambie"
  "Guinea-Bissau"                            : "Guinea-Bissau"
  "Madagascar"                               : "Madagaskar"
  "Mauritania"                               : "Mauritánie"
  "Turkmenistan"                             : "Turkmenistán"
  "Belarus"                                  : "Bělorusko"
  "Burkina Faso"                             : "Burkina Faso"
  "Kyrgyzstan"                               : "Kyrgyzstán"
  "Brazil"                                   : "Brazílie"
  "Senegal"                                  : "Senegal"
  "Nepal"                                    : "Nepál"
  "Rep. of Korea"                            : "Jižní Korea"
  "Dominican Rep."                           : "Dominikánská rep."
  "Grenada"                                  : "Grenada"
  "Jamaica"                                  : "Jamaica"
  "Trinidad and Tobago"                      : "Trinidad a Tobago"
  "Saint Vincent and the Grenadines"         : "Svatý Vincenc a Grenadiny"
  "Zimbabwe"                                 : "Zimbabwe"
  "Mongolia"                                 : "Mongolsko"
  "Bahrain"                                  : "Bahrajn"
  "Tonga"                                    : "Tonga"
  "Saint Lucia"                              : "Svatá Lucie"
  "Benin"                                    : "Benin"
  "Antigua and Barbuda"                      : "Antigua a Barbuda"
  "Barbados"                                 : "Barbados"
  "Dominica"                                 : "Dominika"
  "Bhutan"                                   : "Bhútán"
  "Dem. People's Rep. of Korea"              : "Severní Korea"
  "Timor-Leste"                              : "Timor-Leste"
  "United Arab Emirates"                     : "Spojené arabské emiráty"
  "Japan"                                    : "Japonsko"
  "Belgium"                                  : "Belgie"
  "Brunei Darussalam"                        : "Brunej"
  "Paraguay"                                 : "Paraguay"
  "Montenegro"                               : "Černá Hora"
  "Mauritius"                                : "Mauritius"
  "Singapore"                                : "Singapur"
  "Gabon"                                    : "Gabon"
  "Papua New Guinea"                         : "Papua-Nová Guinea"
  "Botswana"                                 : "Botswana"
  "Comoros"                                  : "Komory"
  "Swaziland"                                : "Svazijsko"
  "Oman"                                     : "Omán"
  "Bahamas"                                  : "Bahamské ostrovy"
  "Solomon Islands"                          : "Šalamounovy ostrovy"
  "Lesotho"                                  : "Lesotho"
  "South Sudan"                              : "Jižní Súdán"
  "Belize"                                   : "Belize"
  "Curacao"                                  : "Curacao"
  "Ireland"                                  : "Irsko"
  "Niue"                                     : "Niue"
  "Cyprus"                                   : "Kypr"
